'use client'

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { CssBaseline, Toolbar } from "@mui/material";
import { usePathname } from "next/navigation";
import CustomLayout from "@/layout/CustomLayout";
import AuthLayout from "@/layout/AuthLayout";


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children }) {
const router = usePathname()

const hideHeaderOnPages = [
  "/auth/login",
];

function getLayout(route) {
  // Define which layout to use based on the route
  if (hideHeaderOnPages.includes(route)) {
    return AuthLayout;
  } else {
    return CustomLayout;
  }
}

const CustomLayoutFull = getLayout(router);
  return (
    <html lang="en">
      <body>  
      <CustomLayoutFull>

      {children}
      </CustomLayoutFull>
      </body>
    </html>
  );
}
